spring.application.name: batch

spring:
  jta:
    enabled: true
    atomikos:
      datasource:
        source:
          unique-resource-name: sourceDataSource
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          xa-properties:
            url: jdbc:mysql://localhost:3306/source_db
            username: source_user
            password: 1234
        batch:
          unique-resource-name: batchDataSource
          xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
          xa-properties:
            url: jdbc:mysql://localhost:13306/batch_db
            username: batch_user
            password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
    open-in-view: false

logging:
  level:
    kr.osci.batch: debug
#    org.springframework: debug